services:
  application:
    build: .
    image: slawekludwiczak/movieclub
    container_name: movieclub
    environment:
      - "DB_URL"
      - "DB_USERNAME"
      - "DB_PASSWORD"
      - "STORAGE_LOCATION"
      - "SPRING_PROFILES_ACTIVE"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: wget --spider localhost:8080
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s
